import assert from "node:assert/strict";
import test from "node:test";
import { NextRequest } from "next/server";
import { POST } from "../app/api/hot-analysis/analyze/route";

const TITLE_AI_RESPONSE = {
  titleStructure: "悬念型",
  contentDirection: ["职场成长"],
  titleAttraction: {
    score: 8,
    reason: "结果与读者利益直接相关",
  },
  topicPotential: {
    score: 7,
    reason: "职场决策具有稳定需求",
  },
  painPointClarity: {
    score: 9,
    painPoint: "努力工作但长期得不到晋升的人",
    reason: "标题明确指向晋升困境",
  },
  ipFit: {
    tier: "高度匹配",
    reason: "符合职场知识IP定位",
  },
  worthContinuing: {
    verdict: "值得补全",
    reason: "痛点明确且有展开空间",
  },
  titleDiagnosisGrade: "A",
  overallSummary: "标题痛点明确，适合补充案例和解决方法。",
};

const TRANSCRIPT_AI_RESPONSE = {
  title: "",
  author: "",
  platform: "",
  publishedAt: "",
  contentDirection: ["职场成长"],
  hook: "为什么越努力的人，越容易错过晋升？",
  hookType: "反常识型",
  hookScore: {
    painPoint: 8,
    curiosity: 8,
    conflict: 7,
    benefit: 7,
    emotion: 6,
    total: 36,
  },
  whyViral: "开头用反差提出职场痛点。",
  structureBreakdownText: "开头提问，中段解释原因，结尾给出建议。",
  contentLayerPassed: true,
  contentLayerMatched: ["明确痛点", "反常识表达"],
  structureLayerPassed: true,
  structureLayerMissing: [],
  exclusionMatched: null,
  selfCheckPassed: true,
  selfCheckReasoning: "观点、案例和行动建议完整。",
  worthLearning: "值得学习",
  worthLearningReason: "反常识开头可以复用。",
  ipFitTier: "高度匹配",
  ipFitReason: "符合职场知识IP定位。",
  titleStructure: "认知颠覆型",
  openingHookType: "反常识",
  userNeedLayer: "知识",
  sentenceStageTags: [
    { index: 0, stage: "Hook" },
    { index: 1, stage: "Solution" },
  ],
  sentenceEmotionTags: [
    { index: 0, emotions: ["好奇"] },
    { index: 1, emotions: ["希望"] },
  ],
  methodCards: [{
    name: "反常识职场开头法",
    targetCategory: "开头方法库",
    summary: "先指出努力与结果之间的反差，再解释真正影响结果的关键因素。",
    evidenceQuote: "为什么越努力的人，越容易错过晋升？",
  }],
};

function deepSeekResponse(content: string) {
  return new Response(JSON.stringify({
    id: "hot-analysis-request",
    choices: [{
      finish_reason: "stop",
      message: { content },
    }],
    usage: {
      prompt_tokens: 100,
      completion_tokens: 300,
    },
  }), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
}

function hotAnalysisRequest(body: unknown) {
  return new NextRequest("http://localhost/api/hot-analysis/analyze", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-DeepSeek-Key": "test-key",
    },
    body: JSON.stringify(body),
  });
}

test("title input is dispatched to title analysis and returns titleEvaluation", async () => {
  const originalFetch = globalThis.fetch;
  let outboundBody = "";
  globalThis.fetch = async (_input, init) => {
    outboundBody = String(init?.body ?? "");
    return deepSeekResponse(JSON.stringify(TITLE_AI_RESPONSE));
  };

  try {
    const response = await POST(hotAnalysisRequest({
      inputType: "title",
      inputRaw: "为什么越努力的人，越容易错过晋升？",
      ipContext: {
        name: "职场教练",
        positioning: "职场知识",
        audience: "职场新人",
        contentDirection: ["职场成长"],
        platforms: ["抖音"],
      },
    }));
    const body = await response.json();

    assert.equal(response.status, 200);
    assert.equal(body.mode, "title");
    assert.equal(body.title, "为什么越努力的人，越容易错过晋升？");
    assert.equal(body.titleEvaluation.titleAttraction.score, 8);
    assert.equal(body.titleEvaluation.titleDiagnosisGrade, "A");
    assert.equal(body.titleStructure, "悬念型");
    assert.deepEqual(body.methodCards, []);
    assert.equal(body.evaluation, null);
    assert.equal(body.dna, null);
    assert.match(outboundBody, /只针对一个标题/);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test("transcript input returns mode and strictly parsed methodCards", async () => {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () =>
    deepSeekResponse(JSON.stringify(TRANSCRIPT_AI_RESPONSE));

  try {
    const response = await POST(hotAnalysisRequest({
      inputType: "transcript",
      inputRaw: "为什么越努力的人，越容易错过晋升？真正重要的是让成果被看见。",
      metrics: null,
    }));
    const body = await response.json();

    assert.equal(response.status, 200);
    assert.equal(body.mode, "transcript");
    assert.equal(body.titleAutoGenerated, true);
    assert.equal(body.titleEvaluation, null);
    assert.equal(body.methodCards.length, 1);
    assert.deepEqual(body.methodCards[0], TRANSCRIPT_AI_RESPONSE.methodCards[0]);
    assert.equal(body.evaluation.hookScore.total, 36);
    assert.equal(body.dna.titleStructure, "认知颠覆型");
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test("copy input keeps copy mode in the response", async () => {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () =>
    deepSeekResponse(JSON.stringify({
      ...TRANSCRIPT_AI_RESPONSE,
      title: "职场晋升的关键",
    }));

  try {
    const response = await POST(hotAnalysisRequest({
      inputType: "copy",
      inputRaw: "职场晋升的关键，不只是努力。",
    }));
    const body = await response.json();

    assert.equal(response.status, 200);
    assert.equal(body.mode, "copy");
    assert.equal(body.title, "职场晋升的关键");
    assert.equal(body.titleAutoGenerated, false);
    assert.equal(body.methodCards.length, 1);
  } finally {
    globalThis.fetch = originalFetch;
  }
});
