import type { TopicBoardResult } from "./topic-board-contract";

export function createValidTopicBoardResult(): TopicBoardResult {
  return {
    contractVersion: 1,
    topic: "普通人如何判断一个机会是否适合自己？",
    ipId: "ip-shuimuran",
    ipName: "水木然",
    experts: [{
      role: "用户需求专家",
      color: "#639922",
      weight: 0.12,
      observation: "用户存在明确判断焦虑。",
      reasoning: "选题能够命中真实决策场景。",
      conclusion: "建议优化后测试。",
      initialScore: 72,
      finalScore: 69,
      scoreChange: -3,
      dimData: {
        dims: [{ label: "痛点强度", score: 7, max: 10 }],
        formula: "7 / 1 × 10 = 70",
        computed: 70,
      },
      vote: "支持",
      veto: false,
      vetoReason: null,
    }],
    chiefOfficer: {
      role: "首席反对官",
      reasons: ["表达角度还不够具体。"],
      riskLevel: "中风险",
      failProbability: 40,
      dismissalSuggestion: "补充具体人群和场景。",
    },
    challenges: [{
      from: "首席反对官",
      to: "用户需求专家",
      targetScore: 72,
      challenge: "用户为什么现在需要这个判断？",
      affectedDimension: "痛点强度",
      impact: "需要下调评分。",
    }],
    responses: [{
      role: "用户需求专家",
      challenge: "用户为什么现在需要这个判断？",
      response: "质疑成立，重新审视后下调评分。",
      initialScore: 72,
      finalScore: 69,
      scoreChange: -3,
      finalFormula: "7 / 1 × 10 = 70",
    }],
    votes: [{ role: "用户需求专家", vote: "支持" }],
    voteResult: { supportCount: 1, reserveCount: 0, opposeCount: 0, verdict: "通过" },
    safetyVeto: false,
    safetyVetoReason: null,
    weights: [{ role: "用户需求专家", score: 69, weight: 0.12, contribution: 8.28 }],
    totalScore: 72,
    level: "B 建议优化后做",
    finalRecommendation: "建议优化后做",
    scoreDisplay: "72",
    beginnerAdvice: {
      canDo: "可以做，但不要直接做现在这个版本。",
      why: "系统参考了历史数据。",
      biggestProblem: "表达角度不够具体。",
      howToImprove: "补充具体人群和场景。",
      shouldTest: "改完后建议小规模测试。",
    },
    confidenceNotice: "本次命中了知识库或历史数据。",
    riskLevel: "中",
    riskExplanation: "表达角度需要验证。",
    scoreBreakdown: [{ label: "IP匹配度", score: 78, explanation: "与当前IP定位匹配。" }],
    dataEvidence: {
      matchedHighPerformance: true,
      matchedCount: 1,
      items: [{
        id: "history-1",
        title: "历史选题",
        source: "发布复盘",
        metricsText: "点赞1200",
        matchReason: "选题方向相近。",
        performanceLevel: "高表现",
      }],
      impact: "历史数据提供正向参考。",
      debugMessage: "匹配到1条高表现样本。",
      calibration: {
        highCount: 1,
        mediumCount: 0,
        lowCount: 0,
        matchedCount: 1,
        dominant: "high",
        hasConflict: false,
        topMatchScore: 8,
      },
    },
    knowledgeDiagnosis: {
      matched: true,
      reason: "命中1条知识库参考。",
      nextStep: "继续补充同类案例。",
    },
    scoringBasis: {
      knowledgeRules: ["使用反常识标题方法。"],
      historicalData: ["历史同类选题表现较好。"],
      ipInfo: ["当前IP：水木然"],
      positiveFactors: ["IP匹配度较高。"],
      negativeFactors: ["场景不够具体。"],
    },
    optimizationPlan: {
      coreReason: "角度需要具体化。",
      keepParts: ["保留机会判断主题。"],
      weakenParts: ["弱化泛泛而谈。"],
      rewrittenDirections: ["增加中年职场人的真实场景。"],
      retestSuggestion: "改写后重新评估。",
    },
    credScore: 68,
    credReasons: ["有历史数据支持。"],
    risks: ["可能过于宽泛。"],
    upgradedTopics: ["40岁以后，普通人如何判断一个机会值不值得押注？"],
    titles: ["真正拉开差距的，不是努力，而是判断机会的能力"],
    personaPreview: null,
    hasPersonas: false,
  };
}
