"use client";
import { apiFetch } from "@/lib/api-fetch";
import { useState, useEffect } from "react";
import { useIP } from "@/lib/ip-context";
import { KnowledgeEntry, HotMaterialAnalysis } from "@/lib/types";
import {
  getKnowledgeEntries, addKnowledgeEntry,
  getHotAnalyses, addHotAnalysis, deleteHotAnalysis, markHotAnalysisAdded,
} from "@/lib/ip-store";
import { Icon } from "@/components/ui/icon";
import { Select } from "@/components/ui/select";

type TabId = "radar" | "genome" | "benchmark" | "predict";
const TABS: { id: TabId; label: string }[] = [
  { id: "radar", label: "素材雷达" },
  { id: "genome", label: "基因库" },
  { id: "benchmark", label: "对标分析" },
  { id: "predict", label: "预测中心" },
];

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <div className={`rounded-[14px] border border-[#E5E4DE] bg-white p-5 ${className}`}>{children}</div>;
}

const GRADE_COLOR: Record<string, { bg: string; text: string }> = {
  "S": { bg: "#FCEBEB", text: "#A32D2D" }, "A": { bg: "#FBF3D6", text: "#7A5C00" },
  "B": { bg: "#EAF3DE", text: "#3B6D11" }, "不收录": { bg: "#F2F1ED", text: "#888" },
};
function GradeBadge({ grade }: { grade: string }) {
  const c = GRADE_COLOR[grade] ?? GRADE_COLOR["不收录"];
  return <span className="rounded-full px-2.5 py-1 text-[11px] font-bold" style={{ background: c.bg, color: c.text }}>{grade === "不收录" ? "C级·不建议学习" : `${grade}级素材`}</span>;
}

const TIER_COLOR: Record<string, { bg: string; text: string }> = {
  "高度匹配": { bg: "#EAF3DE", text: "#3B6D11" }, "中度匹配": { bg: "#FBF3D6", text: "#7A5C00" }, "低度匹配": { bg: "#F2F1ED", text: "#888" },
  "值得学习": { bg: "#EAF3DE", text: "#3B6D11" }, "部分学习": { bg: "#FBF3D6", text: "#7A5C00" }, "不建议学习": { bg: "#FCEBEB", text: "#A32D2D" },
};
function TierTag({ label }: { label: string }) {
  const c = TIER_COLOR[label] ?? { bg: "#F2F1ED", text: "#888" };
  return <span className="rounded-full px-2 py-0.5 text-[10.5px] font-bold" style={{ background: c.bg, color: c.text }}>{label}</span>;
}

// ════════════════════ Tab1 素材雷达 ════════════════════
// 标题模式的 5 项诊断
interface TitleScoreItem { score: number; reason: string }
interface TitlePainPointItem { score: number; painPoint: string; reason: string }
interface TitleFitItem { tier: string | null; reason: string }
interface TitleContinueItem { verdict: string; reason: string }
interface TitleEvaluation {
  titleAttraction: TitleScoreItem;
  topicPotential: TitleScoreItem;
  painPointClarity: TitlePainPointItem;
  ipFit: TitleFitItem;
  worthContinuing: TitleContinueItem;
  titleDiagnosisGrade: string;   // A / B / C
  overallSummary: string;
}

// 逐字稿模式的方法卡
interface MethodCard {
  name: string;
  targetCategory: "定位方法库" | "选题方法库" | "标题方法库" | "开头方法库" | "文案框架方法库";
  summary: string;
  evidenceQuote: string;
  coreMethod?: string;
  applicableScenes?: string[];
  triggerKeywords?: string[];
  aiUsage?: string;
  example?: string;
  unsuitableCases?: string;
}

interface AnalyzeResult {
  mode: "title" | "transcript" | "copy";
  title: string;
  titleAutoGenerated?: boolean;    // 逐字稿模式抽不到标题时置 true
  author: string; platform: string; publishedAt: string; contentDirection: string[];
  // 逐字稿模式字段
  evaluation: HotMaterialAnalysis["evaluation"] | null;
  dna: HotMaterialAnalysis["dna"] | null;
  hasRealMetrics: boolean;
  worthLearning: string; worthLearningReason: string;
  ipFitTier: string | null; ipFitReason: string;
  methodCards: MethodCard[];
  // 标题模式字段
  titleEvaluation: TitleEvaluation | null;
  titleStructure?: string;
}

// 标题模式存进 HotMaterialAnalysis 时，evaluation/dna 用空骨架，历史列表照常显示
const EMPTY_EVAL: HotMaterialAnalysis["evaluation"] = {
  account: "", track: "", hook: "", hookType: null,
  hookScore: { painPoint: 0, curiosity: 0, conflict: 0, benefit: 0, emotion: 0, total: 0 },
  grade: "不收录", whyViral: "", structureBreakdown: "",
  metricsLayerPassed: false, metricsLayerReason: "标题模式不涉及指标层",
  contentLayerPassed: false, contentLayerMatched: [],
  structureLayerPassed: false, structureLayerMissing: [],
  exclusionMatched: null, selfCheckPassed: false, selfCheckReasoning: "标题模式不涉及自我检查",
  admitted: false,
};
const EMPTY_DNA: HotMaterialAnalysis["dna"] = {
  titleStructure: "", openingHookType: "", openingHookText: "",
  structureBreakdown: [], emotionValue: [], userNeedLayer: "",
};

// 标题诊断等级角标（区别于 GradeBadge 的钩子评分等级）
const TITLE_GRADE_COLOR: Record<string, { bg: string; text: string; label: string }> = {
  "A": { bg: "#EAF3DE", text: "#3B6D11", label: "A · 值得补全" },
  "B": { bg: "#FBF3D6", text: "#7A5C00", label: "B · 可以补全" },
  "C": { bg: "#FCEBEB", text: "#A32D2D", label: "C · 不建议补全" },
};
function TitleGradeBadge({ grade }: { grade: string }) {
  const c = TITLE_GRADE_COLOR[grade] ?? TITLE_GRADE_COLOR["C"];
  return <span className="rounded-full px-2.5 py-1 text-[11px] font-bold" style={{ background: c.bg, color: c.text }}>{c.label}</span>;
}

// 分数条：0-10 的 5 项标题诊断专用
function ScoreBar({ score, label }: { score: number; label: string }) {
  const pct = Math.max(0, Math.min(10, score)) * 10;
  return (
    <div className="flex items-center gap-2">
      <span className="w-[92px] flex-shrink-0 text-[11.5px] text-[#666]">{label}</span>
      <div className="h-[8px] flex-1 overflow-hidden rounded-full bg-[#F2F1ED]"><div className="h-full rounded-full bg-[#1C1C1B]" style={{ width: `${pct}%` }} /></div>
      <span className="w-[32px] text-right text-[11px] font-bold text-[#1C1C1B] tabular-nums">{score}/10</span>
    </div>
  );
}

// 分类色标（方法卡预览用，颜色和 knowledge-hub 里保持一致的思路）
const CATEGORY_COLOR: Record<string, string> = {
  "定位方法库": "#C9A8F0", "选题方法库": "#8FB6FF", "标题方法库": "#639922",
  "开头方法库": "#F0C86B", "文案框架方法库": "#E88A66",
};

const METHOD_CATEGORY_FALLBACK: MethodCard["targetCategory"] = "选题方法库";
const METHOD_CATEGORY_MAP: Record<string, MethodCard["targetCategory"]> = {
  "案例": "选题方法库",
  "爆款案例": "选题方法库",
  "方法论": "文案框架方法库",
  "钩子": "开头方法库",
  "Hook": "开头方法库",
  "标题": "标题方法库",
  "评论洞察": "选题方法库",
  "评论需求": "选题方法库",
  "IP语料": "定位方法库",
  "IP语料库": "定位方法库",
  "定位方法库": "定位方法库",
  "选题方法库": "选题方法库",
  "标题方法库": "标题方法库",
  "开头方法库": "开头方法库",
  "文案框架方法库": "文案框架方法库",
};

function normalizeMethodCategory(category: string | undefined): MethodCard["targetCategory"] {
  return category ? (METHOD_CATEGORY_MAP[category] ?? METHOD_CATEGORY_FALLBACK) : METHOD_CATEGORY_FALLBACK;
}

function compactKeywords(parts: Array<string | undefined | null>): string[] {
  return Array.from(new Set(parts.flatMap(part => (part ?? "").split(/[、，,。\s#｜|/]+/)).map(s => s.trim()).filter(Boolean))).slice(0, 8);
}

function normalizeMethodCards(rawCards: unknown, result: AnalyzeResult, inputRaw: string, ipName?: string): MethodCard[] {
  const parsedCards = Array.isArray(rawCards) ? rawCards : [];
  const normalized = parsedCards.map((card: any) => ({
    name: String(card.name ?? card.title ?? "").trim(),
    targetCategory: normalizeMethodCategory(String(card.targetCategory ?? card.category ?? "")),
    summary: String(card.summary ?? card.coreMethod ?? "").trim(),
    evidenceQuote: String(card.evidenceQuote ?? card.example ?? "").trim(),
    coreMethod: String(card.coreMethod ?? card.summary ?? "").trim(),
    applicableScenes: Array.isArray(card.applicableScenes) ? card.applicableScenes.map(String) : [],
    triggerKeywords: Array.isArray(card.triggerKeywords) ? card.triggerKeywords.map(String) : [],
    aiUsage: String(card.aiUsage ?? "").trim(),
    example: String(card.example ?? "").trim(),
    unsuitableCases: String(card.unsuitableCases ?? "").trim(),
  })).filter(card => card.name && card.summary);
  if (normalized.length > 0) return normalized;

  if (result.worthLearning === "不建议学习" && !result.evaluation?.contentLayerPassed) return [];

  const title = result.title || inputRaw.slice(0, 24) || "当前内容";
  const titleStructure = result.dna?.titleStructure || "痛点型";
  const hookType = result.dna?.openingHookType || result.evaluation?.hookType || "反常识";
  const needLayer = result.dna?.userNeedLayer || "用户需求";
  const keywords = compactKeywords([title, titleStructure, hookType, needLayer, ...(result.contentDirection ?? [])]);
  const evidence = result.evaluation?.hook || inputRaw.slice(0, 80);

  const cards: MethodCard[] = [
    {
      name: `${titleStructure}选题法`,
      targetCategory: "选题方法库",
      summary: `把「${title}」这类内容拆成清晰痛点、具体场景和可验证结果，先让用户知道为什么和自己有关。`,
      evidenceQuote: evidence,
      coreMethod: "从用户真实痛点切入，用一个具体场景承接观点，避免停留在泛泛判断。",
      applicableScenes: ["痛点选题", "行业经验拆解", "用户决策类内容"],
      triggerKeywords: keywords,
      aiUsage: "当用户输入类似选题时，先判断痛点是否具体，再帮助补出人群、场景和结果承诺。",
      example: title,
      unsuitableCases: "纯情绪表达、没有具体用户问题或没有可验证经验的内容不适合使用。",
    },
    {
      name: `${needLayer}拆解法`,
      targetCategory: "文案框架方法库",
      summary: `围绕「${needLayer}」组织正文，把问题、原因、判断标准和解决建议分层讲清楚。`,
      evidenceQuote: result.evaluation?.structureBreakdown || evidence,
      coreMethod: "用“问题是什么、为什么会发生、怎么判断、怎么解决”的顺序搭建内容。",
      applicableScenes: ["知识型口播", "经验总结", "避坑清单"],
      triggerKeywords: keywords,
      aiUsage: "用于把一个有价值的观点扩展成更完整的口播结构。",
      example: title,
      unsuitableCases: "只适合展示氛围、不需要解释逻辑的内容不适合强行拆解。",
    },
    {
      name: `${hookType}开头法`,
      targetCategory: "开头方法库",
      summary: `开头先抛出反差、问题或结果，让用户在前几秒知道继续看的理由。`,
      evidenceQuote: evidence,
      coreMethod: "前3秒给出冲突或问题，不先铺背景。",
      applicableScenes: ["短视频开头", "口播钩子", "标题后第一句话"],
      triggerKeywords: compactKeywords([hookType, titleStructure, "开头", "钩子", title]),
      aiUsage: "生成脚本时优先用它压缩开场，让主题更快进入用户痛点。",
      example: evidence,
      unsuitableCases: "严肃通知、纯信息公告不适合过度制造冲突。",
    },
  ];

  if (ipName || result.ipFitTier) {
    cards.push({
      name: `${ipName || "IP"}价值表达法`,
      targetCategory: "定位方法库",
      summary: "把内容价值和账号身份绑定，让用户知道这个观点为什么应该由这个IP来说。",
      evidenceQuote: result.ipFitReason || evidence,
      coreMethod: "用专业经验、身份背景或长期观察支撑观点，增强信任感。",
      applicableScenes: ["个人IP内容", "服务型IP", "专业经验表达"],
      triggerKeywords: compactKeywords([ipName, "IP定位", "信任感", "专业经验", title]),
      aiUsage: "用于判断选题是否符合当前IP，以及如何把观点讲得更像这个账号。",
      example: title,
      unsuitableCases: "和账号定位无关的娱乐化内容不适合强绑定专业身份。",
    });
  }

  return cards;
}

function buildMethodCardContent(card: MethodCard): string {
  return [
    `核心方法：${card.coreMethod || card.summary}`,
    `适用场景：${(card.applicableScenes?.length ? card.applicableScenes : ["短视频内容生产"]).join("、")}`,
    `触发关键词：${(card.triggerKeywords?.length ? card.triggerKeywords : [card.name]).join("、")}`,
    `AI调用方式：${card.aiUsage || "当用户输入相似选题或脚本时，参考此方法判断内容角度和表达结构。"}`,
    `示例：${card.example || card.evidenceQuote || card.name}`,
    `不适用情况：${card.unsuitableCases || "缺少明确用户问题、场景或表达目标时不建议套用。"}`,
  ].join("\n\n");
}

function buildOriginalContentMetadata(inputRaw: string, analysisId: string, sourceUrl: string) {
  return JSON.stringify({
    metadata: {
      originalContent: inputRaw,
      sourceUrl,
      source: "爆款分析中心",
      analysisId,
    },
  });
}

function getViralCaseAdmission(result: AnalyzeResult | null) {
  if (!result?.evaluation) return { canCollect: false, reasons: ["尚未完成分析"] };
  const reasons: string[] = [];
  if (!result.hasRealMetrics) reasons.push("缺少真实互动数据");
  if (!result.evaluation.metricsLayerPassed) reasons.push(result.hasRealMetrics ? "点赞、评论、收藏、分享未达到爆款案例库阈值" : "尚未被验证为高表现内容");
  if (!result.evaluation.contentLayerPassed) reasons.push("内容层证据不足");
  if (!result.evaluation.structureLayerPassed) reasons.push("内容结构不完整");
  if (result.evaluation.exclusionMatched) reasons.push(`命中排除项：${result.evaluation.exclusionMatched}`);
  if (!result.evaluation.selfCheckPassed) reasons.push("自我检查未通过");
  const canCollect = result.hasRealMetrics
    && result.evaluation.metricsLayerPassed
    && result.evaluation.contentLayerPassed
    && result.evaluation.structureLayerPassed
    && !result.evaluation.exclusionMatched
    && result.evaluation.selfCheckPassed;
  return { canCollect, reasons: canCollect ? ["真实数据、内容结构和自我检查均通过，可作为历史表现样本。"] : reasons };
}

function normalizeWorthLearning(value: string): HotMaterialAnalysis["worthLearning"] {
  return value === "值得学习" || value === "部分学习" || value === "不建议学习" ? value : "部分学习";
}

function normalizeIPFitTier(value: string | null): HotMaterialAnalysis["ipFitTier"] {
  return value === "高度匹配" || value === "中度匹配" || value === "低度匹配" ? value : null;
}

function RadarTab() {
  const { activeIP, ips } = useIP();
  const [inputType, setInputType] = useState<"transcript" | "copy" | "title">("transcript");
  const [inputRaw, setInputRaw] = useState("");
  const [sourceUrl, setSourceUrl] = useState("");
  const [hasMetrics, setHasMetrics] = useState(false);
  const [likes, setLikes] = useState(""); const [comments, setComments] = useState("");
  const [shares, setShares] = useState(""); const [favorites, setFavorites] = useState("");
  const [aboveAvg, setAboveAvg] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AnalyzeResult | null>(null);
  const [added, setAdded] = useState(false);
  const [caseAdded, setCaseAdded] = useState(false);
  const [addedCount, setAddedCount] = useState(0);          // 本次入库的条目数（方法卡场景可能 >1）
  const [history, setHistory] = useState<HotMaterialAnalysis[]>([]);
  const [lastAnalysisId, setLastAnalysisId] = useState<string | null>(null);

  useEffect(() => { setHistory(getHotAnalyses()); }, []);

  async function handleAnalyze() {
    if (!inputRaw.trim()) { setError("请提供要分析的内容"); return; }
    setLoading(true); setError(null); setResult(null); setAdded(false); setCaseAdded(false); setAddedCount(0);
    try {
      const res = await apiFetch("/api/hot-analysis/analyze", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          inputType, inputRaw, sourceUrl,
          ipContext: activeIP ? { name: activeIP.name, positioning: activeIP.positioning, audience: activeIP.audience, contentDirection: activeIP.contentDirection, platforms: activeIP.platforms } : null,
          metrics: hasMetrics ? { likes: Number(likes) || 0, comments: Number(comments) || 0, shares: Number(shares) || 0, favorites: Number(favorites) || 0, aboveAccountAverage: aboveAvg } : null,
        }),
      });
      let data: Record<string, any>;
      try {
        data = await res.json();
      } catch {
        setError(res.ok ? "AI返回格式异常" : "AI请求失败");
        return;
      }
      if (!res.ok) {
        if (process.env.NODE_ENV !== "production") {
          console.error("[hot-analysis]", {
            requestId: data.requestId ?? data.apiMeta?.requestId ?? null,
            errorStage: data.errorCode ?? data.apiMeta?.errorStage ?? "request_failed",
          });
        }
        setError(typeof data.error === "string" && data.error ? data.error : "AI请求失败");
        return;
      }
      const normalizedResult = {
        ...data,
        mode: data.mode ?? inputType,
        methodCards: normalizeMethodCards(data.methodCards, data as AnalyzeResult, inputRaw, activeIP?.name),
      } as AnalyzeResult;
      setResult(normalizedResult);

      // ── 存历史：标题模式用空骨架的 evaluation/dna，其余按响应存 ──
      const isTitle = normalizedResult.mode === "title";
      const saved = addHotAnalysis({
        inputType, inputRaw, sourceUrl,
        title: normalizedResult.title, author: normalizedResult.author, platform: normalizedResult.platform, publishedAt: normalizedResult.publishedAt, contentDirection: normalizedResult.contentDirection,
        evaluation: isTitle ? EMPTY_EVAL : (normalizedResult.evaluation ?? EMPTY_EVAL), hasRealMetrics: !!normalizedResult.hasRealMetrics,
        worthLearning: normalizeWorthLearning(normalizedResult.worthLearning), worthLearningReason: normalizedResult.worthLearningReason,
        ipId: activeIP?.id ?? null, ipFitTier: normalizeIPFitTier(normalizedResult.ipFitTier), ipFitReason: normalizedResult.ipFitReason,
        dna: isTitle ? EMPTY_DNA : (normalizedResult.dna ?? EMPTY_DNA),
      });
      setLastAnalysisId(saved.id);
      setHistory(getHotAnalyses());
    } catch {
      setError("AI请求失败");
    } finally { setLoading(false); }
  }

  function handleAddToKB() {
    if (!result || !lastAnalysisId) return;

    // ── 标题模式：作为一条标题案例入到"标题方法库"，原文=标题本身 ──
    if (result.mode === "title") {
      const entry = addKnowledgeEntry({
        category: "标题方法库",
        title: inputRaw.slice(0, 40) || "未命名标题",
        rawContent: buildMethodCardContent({
          name: inputRaw.slice(0, 40) || "标题方法",
          targetCategory: "标题方法库",
          summary: result.titleEvaluation?.overallSummary ?? "标题诊断沉淀",
          evidenceQuote: inputRaw,
          coreMethod: result.titleEvaluation?.overallSummary ?? "根据标题吸引力、选题潜力和痛点清晰度判断标题是否值得继续扩展。",
          applicableScenes: ["标题诊断", "标题优化", "选题补全"],
          triggerKeywords: compactKeywords([inputRaw, result.titleStructure, "标题"]),
          aiUsage: "当用户输入相似标题时，参考此标题结构判断是否值得补全为完整内容。",
          example: inputRaw,
          unsuitableCases: "没有明确对象、场景或利益点的标题不建议直接套用。",
        }),
        tags: [result.titleStructure ?? "标题案例"],
        keywords: [],
        ipId: activeIP?.id ?? null,
        sourceTier: "中",
        sourceTierReason: "标题级素材，未验证完整传播表现",
        contentDirection: result.contentDirection, sourcePlatform: "", sourceUrl,
        note: buildOriginalContentMetadata(inputRaw, lastAnalysisId, sourceUrl),
        extractedAt: new Date().toISOString(),
        metrics: null, viralEvaluation: null, usageRecords: [], status: "未使用", dna: null,
      });
      markHotAnalysisAdded(lastAnalysisId, entry.id);
      setAdded(true); setAddedCount(1); setHistory(getHotAnalyses());
      return;
    }

    // ── 逐字稿/文案模式：拆方法卡入库，原文只作为来源记录写在 note 里 ──
    if (result.methodCards.length === 0) {
      setError("本次分析没有提炼出可复用的方法卡（可能内容偏流水账或质量不足），不建议入库。若确需保留原文，请去知识库中心手动添加。");
      return;
    }
    const sourceLabel = result.title || inputRaw.slice(0, 20);
    const entryIds: string[] = [];
    for (const card of result.methodCards) {
      const entry = addKnowledgeEntry({
        category: card.targetCategory,          // ← 每张卡自动入到对应分类
        title: card.name,                        // ← 方法名做条目标题
        rawContent: buildMethodCardContent(card),
        tags: [card.name, card.targetCategory, ...(card.triggerKeywords ?? []).slice(0, 4)],
        keywords: card.triggerKeywords ?? [],
        ipId: activeIP?.id ?? null,
        sourceTier: result.hasRealMetrics ? "高" : "中",
        sourceTierReason: result.hasRealMetrics
          ? `从「${sourceLabel}」（有真实互动数据）中沉淀`
          : `从「${sourceLabel}」中沉淀，未验证真实传播表现`,
        contentDirection: result.contentDirection,
        sourcePlatform: result.platform || "",
        sourceUrl,
        note: buildOriginalContentMetadata(inputRaw, lastAnalysisId, sourceUrl),
        extractedAt: new Date().toISOString(),
        // 方法论条目不带互动指标 / 整段评估 / DNA —— 这些属于案例级别的元数据
        metrics: null, viralEvaluation: null, dna: null,
        usageRecords: [], status: "未使用",
      });
      entryIds.push(entry.id);
    }
    // markHotAnalysisAdded 接口只支持关联单个 entryId，用第一条作为主关联即可
    markHotAnalysisAdded(lastAnalysisId, entryIds[0]);
    setAdded(true); setAddedCount(entryIds.length); setHistory(getHotAnalyses());
  }

  function handleAddViralCase() {
    if (!result || !lastAnalysisId || !result.evaluation || !result.dna) return;
    const admission = getViralCaseAdmission(result);
    if (!admission.canCollect) {
      setError(`不建议收录到爆款案例库：${admission.reasons.join("；")}`);
      return;
    }
    const entry = addKnowledgeEntry({
      category: "爆款案例",
      title: result.title || inputRaw.slice(0, 40) || "未命名爆款案例",
      rawContent: inputRaw,
      tags: [...result.contentDirection, result.evaluation.hookType ?? "爆款案例"].filter(Boolean) as string[],
      keywords: compactKeywords([result.title, result.evaluation.hookType, result.dna.titleStructure, result.dna.userNeedLayer, ...result.contentDirection]),
      ipId: activeIP?.id ?? null,
      sourceTier: "高",
      sourceTierReason: "由爆款分析中心严格收录：真实互动数据、内容层、结构层和自我检查均通过。",
      contentDirection: result.contentDirection,
      sourcePlatform: result.platform || "",
      sourceUrl,
      note: "严格收录到爆款案例库，适合作为历史表现样本。",
      extractedAt: new Date().toISOString(),
      metrics: {
        likes: Number(likes) || 0,
        comments: Number(comments) || 0,
        shares: Number(shares) || 0,
        favorites: Number(favorites) || 0,
        aboveAccountAverage: aboveAvg,
      },
      viralEvaluation: result.evaluation,
      usageRecords: [],
      status: "未使用",
      dna: result.dna,
    });
    markHotAnalysisAdded(lastAnalysisId, entry.id);
    setCaseAdded(true);
    setHistory(getHotAnalyses());
  }

  const isTitleMode = inputType === "title";
  const viralAdmission = getViralCaseAdmission(result);

  return (
    <div className="flex flex-col gap-5">
      {ips.length === 0 && <div className="rounded-[10px] bg-[#FBF3D6] px-3 py-2 text-[12.5px] text-[#7A5C00]">还没有创建IP，IP匹配度分析会跳过，建议先去IP身份中心创建一个。</div>}
      <Card>
        <div className="mb-3 flex flex-wrap gap-2">
          {([["transcript", "口播逐字稿"], ["copy", "文案"], ["title", "标题"]] as const).map(([id, label]) => (
            <button key={id} onClick={() => setInputType(id)} className="rounded-full px-3.5 py-1.5 text-[12.5px] font-semibold"
              style={inputType === id ? { background: "#1C1C1B", color: "#fff" } : { background: "#F2F1ED", color: "#888" }}>{label}</button>
          ))}
        </div>
        <textarea value={inputRaw} onChange={e => setInputRaw(e.target.value)}
          placeholder={isTitleMode
            ? "粘贴要诊断的标题（一句话，通常不超过30字）"
            : "粘贴内容…（链接没法自动抓取，麻烦把逐字稿/文案粘进来，链接可以填在下面当来源记录）"}
          rows={isTitleMode ? 2 : 6}
          className="w-full resize-y rounded-[14px] border border-[#E5E4DE] bg-[#F7F6F2] px-4 py-3.5 text-[13.5px] leading-6 outline-none focus:border-[#639922]" />
        <input value={sourceUrl} onChange={e => setSourceUrl(e.target.value)} placeholder="来源链接（可选，仅作引用记录）" className="mt-2.5 w-full rounded-[10px] border border-[#E5E4DE] px-3 py-2 text-[13px]" />

        {/* 真实互动数据只对逐字稿/文案模式有意义，标题模式隐藏这一块 */}
        {!isTitleMode && (
          <div className="mt-3 rounded-[12px] bg-[#F7F6F2] p-3">
            <label className="flex items-center gap-2 text-[12.5px] font-semibold text-[#555]">
              <input type="checkbox" checked={hasMetrics} onChange={e => setHasMetrics(e.target.checked)} />
              我知道这条内容的真实互动数据（不填的话，评级只看内容质量，不代表已验证的真实传播表现）
            </label>
            {hasMetrics && (
              <div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">
                <input value={likes} onChange={e => setLikes(e.target.value.replace(/\D/g, ""))} placeholder="点赞" className="rounded-[8px] border border-[#E5E4DE] bg-white px-2.5 py-1.5 text-[12.5px]" />
                <input value={comments} onChange={e => setComments(e.target.value.replace(/\D/g, ""))} placeholder="评论" className="rounded-[8px] border border-[#E5E4DE] bg-white px-2.5 py-1.5 text-[12.5px]" />
                <input value={shares} onChange={e => setShares(e.target.value.replace(/\D/g, ""))} placeholder="转发" className="rounded-[8px] border border-[#E5E4DE] bg-white px-2.5 py-1.5 text-[12.5px]" />
                <input value={favorites} onChange={e => setFavorites(e.target.value.replace(/\D/g, ""))} placeholder="收藏" className="rounded-[8px] border border-[#E5E4DE] bg-white px-2.5 py-1.5 text-[12.5px]" />
              </div>
            )}
            {hasMetrics && (
              <label className="mt-2 flex items-center gap-2 text-[11.5px] text-[#666]">
                <input type="checkbox" checked={aboveAvg} onChange={e => setAboveAvg(e.target.checked)} />
                播放量明显高于账号平均水平
              </label>
            )}
          </div>
        )}

        {error && <div className="mt-3 rounded-[10px] bg-[#FCEBEB] px-3 py-2 text-[12.5px] text-[#A32D2D]">{error}</div>}
        <div className="mt-4 flex justify-end">
          <button onClick={handleAnalyze} disabled={loading || !inputRaw.trim()} className="flex h-[44px] items-center gap-2 rounded-[12px] bg-[#1C1C1B] px-7 text-[13.5px] font-semibold text-white disabled:opacity-40">
            {loading ? "生成中，请稍候，请勿重复点击（最长约2分钟）…" : (isTitleMode ? "诊断标题" : "分析完整内容")}
          </button>
        </div>
      </Card>

      {/* ══════════════ 标题模式结果卡：5 项标题级诊断 ══════════════ */}
      {result && result.mode === "title" && result.titleEvaluation && (
        <Card className="flex flex-col gap-4">
          <div className="flex flex-wrap items-center gap-2">
            <TitleGradeBadge grade={result.titleEvaluation.titleDiagnosisGrade} />
            <span className="text-[12px] text-[#888]">标题结构「{result.titleStructure || "未识别"}」</span>
            {result.ipFitTier && <TierTag label={result.ipFitTier} />}
          </div>

          <div className="rounded-[10px] bg-[#F7F6F2] p-3">
            <div className="mb-1 text-[11px] font-bold text-[#666]">诊断结论</div>
            <p className="text-[12.5px] leading-5 text-[#333]">{result.titleEvaluation.overallSummary || "（AI 未给出总结）"}</p>
          </div>

          <div className="rounded-[12px] border border-[#F0EFE9] p-4">
            <div className="mb-3 text-[11px] font-bold uppercase tracking-widest text-[#A6A39D]">标题级评估（5 项）</div>
            <div className="flex flex-col gap-3">
              <div>
                <ScoreBar score={result.titleEvaluation.titleAttraction.score} label="标题吸引力" />
                {result.titleEvaluation.titleAttraction.reason && <p className="mt-1 pl-[100px] text-[11.5px] leading-5 text-[#666]">{result.titleEvaluation.titleAttraction.reason}</p>}
              </div>
              <div>
                <ScoreBar score={result.titleEvaluation.topicPotential.score} label="选题潜力" />
                {result.titleEvaluation.topicPotential.reason && <p className="mt-1 pl-[100px] text-[11.5px] leading-5 text-[#666]">{result.titleEvaluation.topicPotential.reason}</p>}
              </div>
              <div>
                <ScoreBar score={result.titleEvaluation.painPointClarity.score} label="用户痛点清晰度" />
                {result.titleEvaluation.painPointClarity.painPoint && <p className="mt-1 pl-[100px] text-[11.5px] leading-5 text-[#333]">🎯 指向人群：{result.titleEvaluation.painPointClarity.painPoint}</p>}
                {result.titleEvaluation.painPointClarity.reason && <p className="mt-0.5 pl-[100px] text-[11.5px] leading-5 text-[#666]">{result.titleEvaluation.painPointClarity.reason}</p>}
              </div>
              <div className="flex items-start gap-2">
                <span className="w-[92px] flex-shrink-0 text-[11.5px] text-[#666]">IP 匹配度</span>
                <div className="flex-1">
                  {result.titleEvaluation.ipFit.tier
                    ? <TierTag label={result.titleEvaluation.ipFit.tier} />
                    : <span className="text-[11.5px] text-[#BBB]">未提供 IP 信息</span>}
                  {result.titleEvaluation.ipFit.reason && <p className="mt-1 text-[11.5px] leading-5 text-[#666]">{result.titleEvaluation.ipFit.reason}</p>}
                </div>
              </div>
              <div className="flex items-start gap-2 border-t border-[#F0EFE9] pt-3">
                <span className="w-[92px] flex-shrink-0 text-[11.5px] font-bold text-[#1C1C1B]">是否值得补全</span>
                <div className="flex-1">
                  <TierTag label={result.titleEvaluation.worthContinuing.verdict} />
                  {result.titleEvaluation.worthContinuing.reason && <p className="mt-1 text-[11.5px] leading-5 text-[#333]">{result.titleEvaluation.worthContinuing.reason}</p>}
                </div>
              </div>
            </div>
          </div>

          <div className="flex items-center justify-between border-t border-[#F0EFE9] pt-3">
            <span className="text-[11.5px] text-[#888]">入库位置：标题方法库</span>
            <button onClick={handleAddToKB} disabled={added} className="rounded-[10px] bg-[#1C1C1B] px-5 py-2.5 text-[13px] font-semibold text-white disabled:opacity-40">
              {added ? "已加入标题方法库" : "加入标题方法库"}
            </button>
          </div>
        </Card>
      )}

      {/* ══════════════ 逐字稿/文案模式结果卡：完整评估 + 方法卡 ══════════════ */}
      {result && result.mode !== "title" && result.evaluation && result.dna && (
        <Card className="flex flex-col gap-4">
          <div className="flex flex-wrap items-center gap-2">
            <GradeBadge grade={result.evaluation.grade} />
            <span className="text-[12px] text-[#888]">钩子评分 {result.evaluation.hookScore.total}/50</span>
            <TierTag label={result.worthLearning} />
            {result.ipFitTier && <TierTag label={result.ipFitTier} />}
            {!result.hasRealMetrics && <span className="text-[11px] text-[#BBB]">（未验证真实传播表现）</span>}
          </div>

          <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
            <div className="rounded-[10px] bg-[#F7F6F2] p-3">
              <div className="mb-1 text-[11px] font-bold text-[#666]">基础信息</div>
              {/* 标题回退：AI 抽不到时用开头前 20 字自动生成，明确告诉用户 */}
              {result.titleAutoGenerated ? (
                <p className="text-[12px] leading-5 text-[#444]">
                  <span className="text-[#7A5C00]">📝 未填写标题，系统根据开头自动生成临时标题：</span>
                  <span className="font-semibold text-[#1C1C1B]">「{result.title}」</span>
                </p>
              ) : (
                <p className="text-[12px] text-[#444]">标题：{result.title}</p>
              )}
              <p className="mt-0.5 text-[11.5px] text-[#888]">作者：{result.author || "（未识别）"} · 平台：{result.platform || "（未识别）"}</p>
            </div>
            <div className="rounded-[10px] bg-[#F7F6F2] p-3">
              <div className="mb-1 text-[11px] font-bold text-[#666]">是否值得学习</div>
              <p className="text-[12px] leading-5 text-[#444]">{result.worthLearningReason}</p>
            </div>
            {result.ipFitTier && (
              <div className="rounded-[10px] bg-[#F7F6F2] p-3 sm:col-span-2">
                <div className="mb-1 text-[11px] font-bold text-[#666]">与当前IP「{activeIP?.name}」的匹配度</div>
                <p className="text-[12px] leading-5 text-[#444]">{result.ipFitReason}</p>
              </div>
            )}
          </div>

          <div className="rounded-[10px] bg-[#F7F6F2] p-3">
            <div className="mb-1 text-[11px] font-bold text-[#666]">为什么爆 · 钩子类型：{result.evaluation.hookType}</div>
            <p className="text-[12px] leading-5 text-[#333]">{result.evaluation.whyViral}</p>
          </div>

          <div className="rounded-[12px] border border-[#F0EFE9] p-4">
            <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
              <span className="text-[11px] font-bold uppercase tracking-widest text-[#A6A39D]">爆款案例库收录判断</span>
              <TierTag label={viralAdmission.canCollect ? "值得学习" : "不建议学习"} />
            </div>
            {viralAdmission.canCollect ? (
              <p className="text-[12px] leading-5 text-[#333]">满足真实互动数据、内容结构和自我检查要求，可以收录到爆款案例库，作为后续对标和预测的历史表现样本。</p>
            ) : (
              <div className="flex flex-col gap-2">
                <p className="text-[13px] font-semibold text-[#A32D2D]">不建议收录到爆款案例库</p>
                <div className="flex flex-wrap gap-1.5">
                  {viralAdmission.reasons.map(reason => (
                    <span key={reason} className="rounded-full bg-[#FCEBEB] px-2 py-0.5 text-[10.5px] font-semibold text-[#A32D2D]">{reason}</span>
                  ))}
                </div>
                {result.methodCards.length > 0 && (
                  <p className="text-[12px] leading-5 text-[#555]">但这条内容具备方法论学习价值，建议拆解为方法卡。</p>
                )}
              </div>
            )}
          </div>

          <div>
            <div className="mb-1.5 text-[11px] font-bold text-[#666]">爆款DNA：标题结构「{result.dna.titleStructure}」· 开头钩子「{result.dna.openingHookType}」· 用户需求层「{result.dna.userNeedLayer}」</div>
            <div className="mb-2 flex flex-col gap-1.5">
              {result.dna.structureBreakdown.filter(s => s.percentage > 0).map(s => (
                <div key={s.stage} className="flex items-center gap-2">
                  <span className="w-[70px] flex-shrink-0 text-[11px] text-[#888]">{s.stage}</span>
                  <div className="h-[8px] flex-1 overflow-hidden rounded-full bg-[#F2F1ED]"><div className="h-full rounded-full bg-[#639922]" style={{ width: `${s.percentage}%` }} /></div>
                  <span className="w-[36px] text-right text-[11px] text-[#888]">{s.percentage}%</span>
                </div>
              ))}
            </div>
            {result.dna.emotionValue.length > 0 && (
              <div className="flex flex-wrap gap-1.5">
                {result.dna.emotionValue.map(e => <span key={e.emotion} className="rounded-full bg-[#F2F1ED] px-2 py-0.5 text-[10.5px] text-[#666]">{e.emotion} {e.percentage}%</span>)}
              </div>
            )}
            <p className="mt-1.5 text-[10.5px] text-[#BBB]">占比按句子标签统计字数得出，不是AI凭感觉报的数字</p>
          </div>

          {/* ── 新增：可沉淀的方法卡（问题 3 的核心） ── */}
          <div className="rounded-[12px] border border-[#F0EFE9] p-4">
            <div className="mb-2 flex items-center justify-between">
              <span className="text-[11px] font-bold uppercase tracking-widest text-[#A6A39D]">
                可沉淀的方法 · 共 {result.methodCards.length} 张
              </span>
              {result.methodCards.length === 0 && <span className="text-[11px] text-[#BBB]">AI 认为这条内容没有值得沉淀的独立方法</span>}
            </div>
            {result.methodCards.length > 0 && (
              <div className="flex flex-col gap-2">
                {result.methodCards.map((card, i) => (
                  <div key={i} className="rounded-[10px] bg-[#F7F6F2] p-3">
                    <div className="mb-1 flex items-center gap-2">
                      <span className="h-2 w-2 flex-shrink-0 rounded-full" style={{ background: CATEGORY_COLOR[card.targetCategory] ?? "#888" }} />
                      <span className="flex-1 text-[13px] font-semibold text-[#1C1C1B]">{card.name}</span>
                      <span className="flex-shrink-0 rounded-full bg-white px-2 py-0.5 text-[10.5px] text-[#666]">→ {card.targetCategory}</span>
                    </div>
                    <p className="text-[11.5px] leading-5 text-[#444]">{card.summary}</p>
                    {card.evidenceQuote && <p className="mt-1 border-l-2 border-[#E5E4DE] pl-2 text-[11px] italic text-[#888]">「{card.evidenceQuote}」</p>}
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="flex items-center justify-between border-t border-[#F0EFE9] pt-3">
            <span className="text-[11.5px] text-[#888]">
              {added
                ? `已按分类沉淀 ${addedCount} 张方法卡；原文只保留在素材雷达历史里`
                : result.methodCards.length > 0
                  ? `将拆成 ${result.methodCards.length} 张方法卡，原文只保存到 metadata.originalContent`
                  : "本次没有可沉淀的方法卡"}
            </span>
            <div className="flex flex-wrap justify-end gap-2">
              {viralAdmission.canCollect && (
                <button onClick={handleAddViralCase} disabled={caseAdded}
                  className="rounded-[10px] bg-[#EAF3DE] px-5 py-2.5 text-[13px] font-semibold text-[#3B6D11] disabled:opacity-40">
                  {caseAdded ? "已收录爆款案例" : "收录到爆款案例库"}
                </button>
              )}
              <button onClick={handleAddToKB} disabled={added || result.methodCards.length === 0}
                className="rounded-[10px] bg-[#1C1C1B] px-5 py-2.5 text-[13px] font-semibold text-white disabled:opacity-40">
                {added ? `已入库 (${addedCount})` : "拆解为方法卡"}
              </button>
            </div>
          </div>
        </Card>
      )}

      {history.length > 0 && (
        <div>
          <div className="mb-2 text-[12px] font-bold text-[#888]">历史分析记录（{history.length}）</div>
          <div className="flex flex-col gap-1.5">
            {history.slice(0, 10).map(h => (
              <div key={h.id} className="flex items-center justify-between rounded-[10px] bg-[#F7F6F2] px-3 py-2 text-[12px]">
                <span className="flex items-center gap-2 text-[#444]">
                  <span>{h.title || h.inputRaw.slice(0, 24)}</span>
                  {h.inputType === "title"
                    ? <span className="rounded-full bg-white px-2 py-0.5 text-[10.5px] font-bold text-[#666]">标题诊断</span>
                    : <GradeBadge grade={h.evaluation.grade} />}
                </span>
                <div className="flex items-center gap-2">
                  {h.addedToKnowledgeBase && <span className="text-[10.5px] text-[#3B6D11]">已入库</span>}
                  <button onClick={() => { deleteHotAnalysis(h.id); setHistory(getHotAnalyses()); }} className="text-[#999] hover:text-[#A32D2D]"><Icon name="trash" size="sm" /></button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ════════════════════ Tab2 基因库：纯客户端统计，不调用AI ════════════════════
function GenomeTab() {
  const [entries, setEntries] = useState<KnowledgeEntry[]>([]);
  useEffect(() => { setEntries(getKnowledgeEntries("爆款案例").filter(e => e.dna)); }, []);

  function tally(getKey: (e: KnowledgeEntry) => string | undefined): { key: string; count: number; pct: number }[] {
    const counts = new Map<string, number>();
    entries.forEach(e => { const k = getKey(e); if (k) counts.set(k, (counts.get(k) ?? 0) + 1); });
    const total = entries.length || 1;
    return Array.from(counts.entries()).map(([key, count]) => ({ key, count, pct: Math.round((count / total) * 100) })).sort((a, b) => b.count - a.count);
  }

  const titleStructures = tally(e => e.dna?.titleStructure);
  const hookTypes = tally(e => e.dna?.openingHookType);
  const needLayers = tally(e => e.dna?.userNeedLayer);

  function Bars({ title, data }: { title: string; data: { key: string; count: number; pct: number }[] }) {
    return (
      <Card>
        <div className="mb-3 text-[13px] font-bold text-[#1C1C1B]">{title}</div>
        {data.length === 0 ? <p className="text-[12px] text-[#999]">暂无数据</p> : (
          <div className="flex flex-col gap-2">
            {data.map(d => (
              <div key={d.key} className="flex items-center gap-2">
                <span className="w-[90px] flex-shrink-0 text-[12px] text-[#555]">{d.key}</span>
                <div className="h-[10px] flex-1 overflow-hidden rounded-full bg-[#F2F1ED]"><div className="h-full rounded-full bg-[#639922]" style={{ width: `${d.pct}%` }} /></div>
                <span className="w-[60px] text-right text-[11.5px] text-[#888]">{d.pct}%（{d.count}条）</span>
              </div>
            ))}
          </div>
        )}
      </Card>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="rounded-[10px] bg-[#F7F6F2] px-3.5 py-2.5 text-[12.5px] text-[#666]">
        基于你知识库中已收录的 <b>{entries.length}</b> 条爆款案例统计——这是你自己积累的素材规律，不是全网/行业统计，数据越多统计越有意义。
      </div>
      <Bars title="标题结构分布" data={titleStructures} />
      <Bars title="开头钩子类型分布" data={hookTypes} />
      <Bars title="用户需求层分布" data={needLayers} />
    </div>
  );
}

// ════════════════════ Tab3 对标分析 ════════════════════
function BenchmarkTab() {
  const [myContent, setMyContent] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<{ titleGap: string; hookGap: string; caseGap: string; conversionGap: string; trustGap: string; rhythmGap: { myHookPercentage: number; avgComparableHookPercentage: number | null; note: string }; comparedCount: number } | null>(null);

  async function handleCompare() {
    if (!myContent.trim()) { setError("请提供你的文案或逐字稿"); return; }
    setLoading(true); setError(null); setResult(null);
    try {
      const allCases = getKnowledgeEntries("爆款案例");
      if (allCases.length === 0) { setError("知识库里还没有爆款案例，请先去素材雷达或知识库中心积累一些"); return; }
      const searchRes = await apiFetch("/api/knowledge-search", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: myContent, entries: allCases.map(e => ({ id: e.id, category: e.category, title: e.title, tags: e.tags, keywords: e.keywords })) }),
      });
      const searchData = await searchRes.json();
      const matchedIds = new Set((searchData.results ?? []).map((r: { id: string }) => r.id));
      const comparables = allCases.filter(e => matchedIds.has(e.id));
      const finalComparables = comparables.length > 0 ? comparables : allCases.slice(0, 5);

      const res = await apiFetch("/api/hot-analysis/benchmark", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          myContent,
          comparables: finalComparables.map(e => ({ id: e.id, title: e.title, rawContent: e.rawContent, hookPercentage: e.dna?.structureBreakdown.find(s => s.stage === "Hook")?.percentage ?? null, hookType: e.viralEvaluation?.hookType ?? null })),
        }),
      });
      const data = await res.json();
      if (!res.ok) { setError(data.error ?? `请求失败（${res.status}）`); return; }
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "对标分析失败");
    } finally { setLoading(false); }
  }

  return (
    <div className="flex flex-col gap-5">
      <Card>
        <textarea value={myContent} onChange={e => setMyContent(e.target.value)} placeholder="粘贴你的文案或逐字稿…" rows={7}
          className="w-full resize-y rounded-[14px] border border-[#E5E4DE] bg-[#F7F6F2] px-4 py-3.5 text-[13.5px] leading-6 outline-none focus:border-[#639922]" />
        {error && <div className="mt-3 rounded-[10px] bg-[#FCEBEB] px-3 py-2 text-[12.5px] text-[#A32D2D]">{error}</div>}
        <div className="mt-4 flex justify-end">
          <button onClick={handleCompare} disabled={loading || !myContent.trim()} className="flex h-[44px] items-center gap-2 rounded-[12px] bg-[#1C1C1B] px-7 text-[13.5px] font-semibold text-white disabled:opacity-40">
            {loading ? "对标中…" : "开始对标"}
          </button>
        </div>
      </Card>

      {result && (
        <Card className="flex flex-col gap-3">
          <div className="text-[11px] text-[#999]">对标了知识库中 {result.comparedCount} 条相关爆款案例</div>
          <div className="rounded-[10px] bg-[#F7F6F2] p-3">
            <div className="mb-1 text-[11px] font-bold text-[#666]">节奏差距</div>
            <p className="text-[12px] leading-5 text-[#444]">
              你的开头铺垫占比 {result.rhythmGap.myHookPercentage}%
              {result.rhythmGap.avgComparableHookPercentage != null && ` · 对标案例平均 ${result.rhythmGap.avgComparableHookPercentage}%`}
            </p>
            <p className="mt-1 text-[11.5px] text-[#888]">{result.rhythmGap.note}</p>
          </div>
          {([["标题差距", result.titleGap], ["钩子差距", result.hookGap], ["案例差距", result.caseGap], ["转化差距", result.conversionGap], ["信任感差距", result.trustGap]] as [string, string][]).map(([label, text]) => (
            <div key={label} className="rounded-[10px] bg-[#F7F6F2] p-3">
              <div className="mb-1 text-[11px] font-bold text-[#666]">{label}</div>
              <p className="text-[12px] leading-5 text-[#444]">{text}</p>
            </div>
          ))}
        </Card>
      )}
    </div>
  );
}

// ════════════════════ Tab4 预测中心 ════════════════════
function PredictTab() {
  const [title, setTitle] = useState("");
  const [script, setScript] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<{ scores: { dimension: string; score: number; matchReasoning: string }[]; comparedCount: number; withRealDataCount: number; avgMetrics: Record<string, number | null>; confidenceNote: string } | null>(null);

  async function handlePredict() {
    if (!title.trim() && !script.trim()) { setError("请至少填写标题或口播稿其中一项"); return; }
    setLoading(true); setError(null); setResult(null);
    try {
      const allCases = getKnowledgeEntries("爆款案例");
      if (allCases.length === 0) { setError("知识库暂无可比案例，无法给出有依据的预测。请先积累一些爆款案例。"); return; }
      const query = `${title}\n${script}`;
      const searchRes = await apiFetch("/api/knowledge-search", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query, entries: allCases.map(e => ({ id: e.id, category: e.category, title: e.title, tags: e.tags, keywords: e.keywords })) }),
      });
      const searchData = await searchRes.json();
      const matchedIds = new Set((searchData.results ?? []).map((r: { id: string }) => r.id));
      const comparables = allCases.filter(e => matchedIds.has(e.id));
      const finalComparables = comparables.length > 0 ? comparables : allCases.slice(0, 5);

      const res = await apiFetch("/api/hot-analysis/predict", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title, script,
          comparables: finalComparables.map(e => ({ id: e.id, title: e.title, rawContent: e.rawContent, metrics: e.metrics, hookType: e.viralEvaluation?.hookType ?? null })),
        }),
      });
      const data = await res.json();
      if (!res.ok) { setError(data.error ?? `请求失败（${res.status}）`); return; }
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "预测失败");
    } finally { setLoading(false); }
  }

  return (
    <div className="flex flex-col gap-5">
      <Card>
        <input value={title} onChange={e => setTitle(e.target.value)} placeholder="标题" className="mb-2.5 w-full rounded-[10px] border border-[#E5E4DE] px-3 py-2.5 text-[13.5px]" />
        <textarea value={script} onChange={e => setScript(e.target.value)} placeholder="口播稿…" rows={6}
          className="w-full resize-y rounded-[14px] border border-[#E5E4DE] bg-[#F7F6F2] px-4 py-3.5 text-[13.5px] leading-6 outline-none focus:border-[#639922]" />
        {error && <div className="mt-3 rounded-[10px] bg-[#FCEBEB] px-3 py-2 text-[12.5px] text-[#A32D2D]">{error}</div>}
        <div className="mt-4 flex justify-end">
          <button onClick={handlePredict} disabled={loading || (!title.trim() && !script.trim())} className="flex h-[44px] items-center gap-2 rounded-[12px] bg-[#1C1C1B] px-7 text-[13.5px] font-semibold text-white disabled:opacity-40">
            {loading ? "预测中…" : "开始预测"}
          </button>
        </div>
      </Card>

      {result && (
        <Card className="flex flex-col gap-3">
          <div className="rounded-[10px] bg-[#FBF3D6] px-3 py-2 text-[11.5px] text-[#7A5C00]">{result.confidenceNote}</div>
          <div className="text-[11px] text-[#999]">
            对标 {result.comparedCount} 条相关案例，其中 {result.withRealDataCount} 条带真实互动数据
            {result.avgMetrics.likes != null && ` · 平均点赞${result.avgMetrics.likes} 平均收藏${result.avgMetrics.favorites}`}
          </div>
          <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
            {result.scores.map(s => (
              <div key={s.dimension} className="rounded-[10px] bg-[#F7F6F2] p-3">
                <div className="mb-1 flex items-center justify-between">
                  <span className="text-[12px] font-bold text-[#1C1C1B]">{s.dimension}</span>
                  <span className="text-[16px] font-bold text-[#639922]">{s.score}</span>
                </div>
                <p className="text-[11.5px] leading-5 text-[#666]">{s.matchReasoning}</p>
              </div>
            ))}
          </div>
        </Card>
      )}
    </div>
  );
}

// ════════════════════ Main ════════════════════
export default function HotAnalysisPage() {
  const [tab, setTab] = useState<TabId>("radar");

  return (
    <div className="min-h-screen p-6 md:p-8">
      <header className="mb-6 flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="mb-1.5 text-[13px] text-[#8A8A86]">
            <a href="/" className="font-semibold text-[#639922]">工作台</a> / 爆款分析中心
          </div>
          <h1 className="text-[24px] font-semibold tracking-tight text-[#1C1C1B]">爆款分析中心</h1>
          <p className="mt-1.5 max-w-[600px] text-[13.5px] leading-6 text-[#8A8A86]">
            爆款发现 → 沉淀 → 拆解 → 知识库 → 对标 → 预测，整个内容生产系统的情报中心
          </p>
        </div>
        <span className="whitespace-nowrap rounded-full bg-[#EAF3DE] px-3.5 py-1.5 text-[12px] font-semibold text-[#3B6D11]">05 · 情报分析</span>
      </header>

      <div className="mb-5 flex flex-wrap gap-2">
        {TABS.map(t => (
          <button key={t.id} onClick={() => setTab(t.id)} className="rounded-[12px] px-4 py-2.5 text-[13px] font-semibold transition-all"
            style={tab === t.id ? { background: "#1C1C1B", color: "#fff" } : { background: "#F2F1ED", color: "#666" }}>
            {t.label}
          </button>
        ))}
      </div>

      {tab === "radar" && <RadarTab />}
      {tab === "genome" && <GenomeTab />}
      {tab === "benchmark" && <BenchmarkTab />}
      {tab === "predict" && <PredictTab />}
    </div>
  );
}
